# src/constants.py or src/enums.py
from enum import Enum

class TagLabels(Enum):
    TITULO_EXACTO = 'titulo_exacto'
    TITULO = 'titulo'
    TITULO_PARCIAL = 'titulo_parcial'
    TITULO_NEGATIVO = 'titulo_negativo'
    ORQUESTA_EXACTA = 'orquesta_exacta'
    ORQUESTA = 'orquesta'
    ORQUESTA_PARCIAL = 'orquesta_parcial'
    ORQUESTA_NEGATIVO = 'orquesta_negativo'
    CANTOR_EXACTO = 'cantor_exacto'
    CANTOR = 'cantor'
    CANTOR_PARCIAL = 'cantor_parcial'
    CANTOR_NEGATIVO = 'cantor_parcial'
    FECHA_EXACTA = 'fecha_exacta'
    FECHA = 'fecha'
    FECHA_PARCIAL = 'fecha_parcial'
    FECHA_NEGATIVA = 'fecha_negativa'
    GENERO_EXACTO = 'genero_exacto'
    GENERO = 'genero'
    GENERO_PARCIAL = 'genero_parcial'
    GENERO_NEGATIVO = 'genero_negativo'
    COMPOSITOR_AUTOR_EXACTO = 'compositor_autor_exacto'
    COMPOSITOR_AUTOR = 'compositor_autor'
    COMPOSITOR_AUTOR_PARCIAL = 'compositor_autor_parcial'
    COMPOSITOR_AUTOR_NEGATIVO = 'compositor_autor_negativo'
    TODO = 'todo'
